export type SaveConfigTypes =
  | 'STAGE_POMODORO_TIME'
  | 'STAGE_SHORT_TIME'
  | 'STAGE_LONG_TIME'
  | 'STAGE_CYCLES'
  | 'SET_IS_SAVED'
  | 'SET_SHOULD_UPDATE_INPUT_VALUE'
  | 'SET_SHOULD_SHOW_SAVE_ALERT'
